local generic = "这是一块地皮。"
local generic2 = "一些拼凑在一起的平整石头。"

local wollow = "无趣的地皮。"
local wollow2 = "无趣的路面。"

local wolfgang = "垫脚石。"

local wendy = "一些地皮。"
local wendy2 = "一些路面。"

local wx78 = "检测到：地面零件"

local wickerbottom = "地皮。你可以踩上去。"

local woodie = "无他，地皮耳。"

local waxwell = "草皮。"
local waxwell2 = "平整的石路。"
local waxwell3 = "黏糊糊的。"
local waxwell4 = "肥沃的地块。"
local waxwell5 = "够坚实的地面。"
local waxwell6 = "坚实的地基。"

local wathgrithr = "战场的小地块。"
local wathgrithr2 = "条条大路通战场。"

local webber = "被挖起来的地皮。"
local webber2 = "被挖起来的路面。"

local winona = "地皮一块。"

--砖路
GLOBAL.STRINGS.NAMES.MONE_TURF_COBBLEROAD = "砖石路"
GLOBAL.STRINGS.RECIPE_DESC.MONE_TURF_COBBLEROAD = "承载着村庄繁荣生活。"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONE_TURF_COBBLEROAD = generic2
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.MONE_TURF_COBBLEROAD = wollow2
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MONE_TURF_COBBLEROAD = wolfgang
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.MONE_TURF_COBBLEROAD = wendy2
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.MONE_TURF_COBBLEROAD = wx78
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MONE_TURF_COBBLEROAD = wickerbottom
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.MONE_TURF_COBBLEROAD = woodie
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MONE_TURF_COBBLEROAD = waxwell2
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MONE_TURF_COBBLEROAD = wathgrithr2
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.MONE_TURF_COBBLEROAD = webber2
GLOBAL.STRINGS.CHARACTERS.WINONA.DESCRIBE.MONE_TURF_COBBLEROAD = winona

--密林地皮
GLOBAL.STRINGS.NAMES.MONE_TURF_DEEPRAINFOREST = "密林地皮"
GLOBAL.STRINGS.RECIPE_DESC.MONE_TURF_DEEPRAINFOREST = "疏影暗香藏隐士，密林深处有人居。"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONE_TURF_DEEPRAINFOREST = generic
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.MONE_TURF_DEEPRAINFOREST = wollow
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MONE_TURF_DEEPRAINFOREST = wolfgang
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.MONE_TURF_DEEPRAINFOREST = wendy
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.MONE_TURF_DEEPRAINFOREST = wx78
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MONE_TURF_DEEPRAINFOREST = wickerbottom
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.MONE_TURF_DEEPRAINFOREST = woodie
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MONE_TURF_DEEPRAINFOREST = waxwell4
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MONE_TURF_DEEPRAINFOREST = wathgrithr
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.MONE_TURF_DEEPRAINFOREST = webber
GLOBAL.STRINGS.CHARACTERS.WINONA.DESCRIBE.MONE_TURF_DEEPRAINFOREST = winona

-- "耕地地皮"
GLOBAL.STRINGS.NAMES.MONE_TURF_FIELDS = "耕地地皮"
GLOBAL.STRINGS.RECIPE_DESC.MONE_TURF_FIELDS = "孕育着文明。"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONE_TURF_FIELDS = generic
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.MONE_TURF_FIELDS = wollow
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MONE_TURF_FIELDS = wolfgang
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.MONE_TURF_FIELDS = wendy
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.MONE_TURF_FIELDS = wx78
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MONE_TURF_FIELDS = wickerbottom
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.MONE_TURF_FIELDS = woodie
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MONE_TURF_FIELDS = waxwell
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MONE_TURF_FIELDS = wathgrithr
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.MONE_TURF_FIELDS = webber
GLOBAL.STRINGS.CHARACTERS.WINONA.DESCRIBE.MONE_TURF_FIELDS = winona

-- "地基地面"
GLOBAL.STRINGS.NAMES.MONE_TURF_FOUNDATION = "地基地面"
GLOBAL.STRINGS.RECIPE_DESC.MONE_TURF_FOUNDATION = "村庄建设的坚实基础。"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONE_TURF_FOUNDATION = generic
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.MONE_TURF_FOUNDATION = wollow
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MONE_TURF_FOUNDATION = wolfgang
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.MONE_TURF_FOUNDATION = wendy
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.MONE_TURF_FOUNDATION = wx78
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MONE_TURF_FOUNDATION = wickerbottom
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.MONE_TURF_FOUNDATION = woodie
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MONE_TURF_FOUNDATION = waxwell6
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MONE_TURF_FOUNDATION = wathgrithr
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.MONE_TURF_FOUNDATION = webber
GLOBAL.STRINGS.CHARACTERS.WINONA.DESCRIBE.MONE_TURF_FOUNDATION = winona

-- "毒性地皮"
GLOBAL.STRINGS.NAMES.MONE_TURF_GASJUNGLE = "毒性地皮"
GLOBAL.STRINGS.RECIPE_DESC.MONE_TURF_GASJUNGLE = "瘴气丛林。"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONE_TURF_GASJUNGLE = generic
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.MONE_TURF_GASJUNGLE = wollow
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MONE_TURF_GASJUNGLE = wolfgang
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.MONE_TURF_GASJUNGLE = wendy
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.MONE_TURF_GASJUNGLE = wx78
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MONE_TURF_GASJUNGLE = wickerbottom
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.MONE_TURF_GASJUNGLE = woodie
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MONE_TURF_GASJUNGLE = waxwell
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MONE_TURF_GASJUNGLE = wathgrithr
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.MONE_TURF_GASJUNGLE = webber
GLOBAL.STRINGS.CHARACTERS.WINONA.DESCRIBE.MONE_TURF_GASJUNGLE = winona

-- "方格草坪"
GLOBAL.STRINGS.NAMES.MONE_TURF_LAWN = "方格草坪"
GLOBAL.STRINGS.RECIPE_DESC.MONE_TURF_LAWN = "严格修整的草坪。"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONE_TURF_LAWN = generic
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.MONE_TURF_LAWN = wollow
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MONE_TURF_LAWN = wolfgang
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.MONE_TURF_LAWN = wendy
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.MONE_TURF_LAWN = wx78
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MONE_TURF_LAWN = wickerbottom
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.MONE_TURF_LAWN = woodie
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MONE_TURF_LAWN = waxwell
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MONE_TURF_LAWN = wathgrithr
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.MONE_TURF_LAWN = webber
GLOBAL.STRINGS.CHARACTERS.WINONA.DESCRIBE.MONE_TURF_LAWN = winona

-- "苔藓地皮"
GLOBAL.STRINGS.NAMES.MONE_TURF_MOSS = "苔藓地皮"
GLOBAL.STRINGS.RECIPE_DESC.MONE_TURF_MOSS = "白日不到处，青春恰自来。"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONE_TURF_MOSS = generic
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.MONE_TURF_MOSS = wollow
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MONE_TURF_MOSS = wolfgang
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.MONE_TURF_MOSS = wendy
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.MONE_TURF_MOSS = wx78
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MONE_TURF_MOSS = wickerbottom
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.MONE_TURF_MOSS = woodie
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MONE_TURF_MOSS = waxwell3
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MONE_TURF_MOSS = wathgrithr
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.MONE_TURF_MOSS = webber
GLOBAL.STRINGS.CHARACTERS.WINONA.DESCRIBE.MONE_TURF_MOSS = winona

-- "遗迹地皮"
GLOBAL.STRINGS.NAMES.MONE_TURF_PIGRUINS = "遗迹地皮"
GLOBAL.STRINGS.RECIPE_DESC.MONE_TURF_PIGRUINS = "的确是有些历史了。"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONE_TURF_PIGRUINS = generic
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.MONE_TURF_PIGRUINS = wollow
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MONE_TURF_PIGRUINS = wolfgang
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.MONE_TURF_PIGRUINS = wendy
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.MONE_TURF_PIGRUINS = wx78
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MONE_TURF_PIGRUINS = wickerbottom
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.MONE_TURF_PIGRUINS = woodie
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MONE_TURF_PIGRUINS = waxwell5
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MONE_TURF_PIGRUINS = wathgrithr
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.MONE_TURF_PIGRUINS = webber
GLOBAL.STRINGS.CHARACTERS.WINONA.DESCRIBE.MONE_TURF_PIGRUINS = winona

-- "雨林地皮"
GLOBAL.STRINGS.NAMES.MONE_TURF_RAINFOREST = "雨林地皮"
GLOBAL.STRINGS.RECIPE_DESC.MONE_TURF_RAINFOREST = "哦，雨林。"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONE_TURF_RAINFOREST = generic
GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.MONE_TURF_RAINFOREST = wollow
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MONE_TURF_RAINFOREST = wolfgang
GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.MONE_TURF_RAINFOREST = wendy
GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.MONE_TURF_RAINFOREST = wx78
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MONE_TURF_RAINFOREST = wickerbottom
GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.MONE_TURF_RAINFOREST = woodie
GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MONE_TURF_RAINFOREST = waxwell4
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MONE_TURF_RAINFOREST = wathgrithr
GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.MONE_TURF_RAINFOREST = webber
GLOBAL.STRINGS.CHARACTERS.WINONA.DESCRIBE.MONE_TURF_RAINFOREST = winona
